{"name": "test_invalidCredentials2", "status": "failed", "statusDetails": {"message": "AssertionError: assert '.DialerActivity' in '.MainActivity'\n +  where '.MainActivity' = <appium.webdriver.webdriver.WebDriver (session=\"923840a6-b269-4ce1-a95e-0607bcd3c682\")>.current_activity", "trace": "test_setup = None\n\n    @allure.description(\"Ingresar credenciales inválidas y permanecer en la pantalla Login (parte 2).\")\n    def test_invalidCredentials2(test_setup):\n        driver.find_element(\"id\", 'com.example.mylogin:id/inputUsername').send_keys(\"fernando\")\n        driver.find_element(\"id\", 'com.example.mylogin:id/inputPassword').send_keys(\"admin\")\n        driver.find_element(\"id\", 'com.example.mylogin:id/btnLogin').click()\n        try:\n>           assert \".DialerActivity\" in driver.current_activity\nE           assert '.DialerActivity' in '.MainActivity'\nE            +  where '.MainActivity' = <appium.webdriver.webdriver.WebDriver (session=\"923840a6-b269-4ce1-a95e-0607bcd3c682\")>.current_activity\n\nLoginFer_test.py:50: AssertionError"}, "description": "Ingresar credenciales inválidas y permanecer en la pantalla Login (parte 2).", "attachments": [{"name": "Invalid Credentials", "source": "9c13b532-7352-4ca6-bf18-c6e71b758d5e-attachment.png", "type": "image/png"}], "start": 1667391438611, "stop": 1667391442605, "uuid": "aa873307-6840-4ead-a490-8fa1aac3d620", "historyId": "8cda61706ab0e0874d31c092d807e0cc", "testCaseId": "c70e4597dd588d0460085b3f4be1b2a6", "fullName": "LoginFer_test#test_invalidCredentials2", "labels": [{"name": "suite", "value": "LoginFer_test"}, {"name": "host", "value": "11LAP5CG00129ZR"}, {"name": "thread", "value": "39284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "LoginFer_test"}]}